USE `test`;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
  `ID`       BIGINT(11)     NOT NULL AUTO_INCREMENT,
  `NAME`     VARBINARY(50)  NOT NULL,
  `PASSWORD` VARBINARY(255) NOT NULL,
  PRIMARY KEY (`ID`)
);

SHOW CREATE DATABASE `test`;
SHOW CREATE TABLE `USER`;