-- MySQL Script generated by MySQL Workbench
-- 2016年05月12日 星期四 23时24分07秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spring-date-demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USER` ;

CREATE TABLE IF NOT EXISTS `USER` (
  `ID` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(50) NOT NULL COMMENT '用户名',
  `PASSWORD` VARCHAR(255) NOT NULL COMMENT '密码',
  `GENDER_CODE` TINYINT(2) ZEROFILL NOT NULL DEFAULT 1 COMMENT '性别 1-男，2-女',
  `EMAIL` VARCHAR(50) NULL COMMENT '邮箱地址',
  `IS_ACTIVE` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `MENU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MENU` ;

CREATE TABLE IF NOT EXISTS `MENU` (
  `ID` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(50) NOT NULL COMMENT '菜单名称',
  `IS_SYSTEM` TINYINT(1) NOT NULL COMMENT '是否系统 true(1)-是，false(0)-否',
  `STATE` VARCHAR(100) NOT NULL COMMENT '菜单对应的路由名称',
  `ICON_URL` VARCHAR(255) NULL COMMENT '菜单图标URL',
  `PARENT_ID` BIGINT(11) NULL COMMENT '父菜单ID',
  `IS_SHORTCUT_MENU` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否快捷菜单 true(1)-是，false(0)-否',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
COMMENT = '菜单表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
